project_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('companies/', include('companies.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path
from . import views


app_name = 'projects'

urlpatterns = [
	path('', views.project_list, name='project_list'),
	path('<int:project_id>', views.project_detail, name='project_detail'),
	path('<int:project_id>/tasks/', views.task_list, name='task_list'),
	path('<int:project_id>/tasks/<int:task_id>', views.task_detail, name='task_detail'),
	path('create_project/', views.create_project, name='create_project'),
	path('create_task/', views.create_task, name='create_task'),
	path('create_issue/', views.create_issue, name='create_issue'),
	path('issues/', views.issue_list, name='issue_list'),
	path('issues/<int:issue_id>', views.issue_detail, name='issue_detail'),
	]

projects/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


status = (
	('C', 'Completed'),
	('A', 'Active'),
	('P', 'Paused'),
	('S', 'Stuck'),
	)

priority = (
	('L', 'Low-priority'),
	('I', 'Important'),
	('N', 'Not important'),
	('U', 'Urgent'),
	('X', 'Xtra Important'),
	)

due = (
	('C', 'Completed'),
	('O', 'Overdue'),
	('D', 'Due'),
	('E', 'Eliminated'),
	)

danger_level = (
	('1', 'Minor'),
	('2', 'Moderate'),
	('3', 'Critical'),
	('4', 'Dangerous'),
	)

class Comment(models.Model):
	user = models.ManyToManyField(User)
	comment = models.CharField(max_length=500)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)


class Project(models.Model):
	company = models.ForeignKey('companies.Company', on_delete=models.CASCADE)

	title = models.CharField(max_length=300, db_index=True)
	slug = models.SlugField(max_length=300, db_index=True, unique=True)
	user = models.ManyToManyField(User)
	
	description = models.TextField(blank=True)

	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	deadline = models.DateField()

	status = models.CharField(max_length=50, choices=status)
	budget = models.DecimalField(max_digits=12, decimal_places=2)

	class Meta:
		ordering = ('title',)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('projects:project_detail', args=[self.id])


class Task(models.Model):
	project = models.ForeignKey(Project, on_delete=models.CASCADE)
	title = models.CharField(max_length=300, db_index=True)
	slug = models.SlugField(max_length=300)
	user = models.ManyToManyField(User)

	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	description = models.TextField()
	priority = models.CharField(max_length=50, choices=priority)
	status = models.CharField(max_length=50, choices=due)

	class Meta:
		ordering = ('title',)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('projects:task_detail', args=[self.project.id, self.id])


class Issue(models.Model):
	title = models.CharField(max_length=150, db_index=True)
	description = models.TextField()
	image = models.ImageField(upload_to="issues/%Y/%m/%d", blank=True)

	threat_level = models.CharField(max_length=50, choices=danger_level)

	deadline = models.DateTimeField()
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	submitted_by = models.ManyToManyField(User, default='')

	project = models.ForeignKey(Project, on_delete=models.CASCADE, blank=True)
	task = models.ForeignKey(Task, on_delete=models.PROTECT, blank=True)

	class Meta:
		ordering = ('created',)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('projects:issue_detail', args=[self.id])

projects/forms.py
from django import forms
from .models import Project, Task, Issue, Comment


class ProjectCreationForm(forms.ModelForm):
	class Meta:
		model = Project
		fields = ['company', 'title', 'description', 'user', 'deadline', 'status', 'budget']


class TaskCreationForm(forms.ModelForm):
	class Meta:
		model = Task
		fields = ['title', 'project', 'user', 'description', 'priority', 'status']


class IssueCreationForm(forms.ModelForm):
	class Meta:
		model = Issue
		fields = ['title', 'description', 'image', 'threat_level', 'deadline', 'project', 'task', 'submitted_by']
		widgets = {
			'deadline': forms.widgets.DateInput(attrs={'type': 'date'})
		}


class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ['user', 'comment']

projects/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

from .models import Project, Task, Issue
from .forms import ProjectCreationForm, TaskCreationForm, IssueCreationForm


def project_list(request):
	projects = Project.objects.all()
	return render(request, "projects/list.html", {'projects': projects})


def project_detail(request, project_id):
	project = get_object_or_404(Project, pk=project_id)
	return render(request, "projects/detail.html", {'project': project})


def task_list(request, project_id):
	project = get_object_or_404(Project, pk=project_id)
	tasks = Task.objects.filter(project=project)
	return render(request, "projects/task_list.html", {"project": project, "tasks": tasks})


def task_detail(request, project_id, task_id):
	project = get_object_or_404(Project, id=project_id)
	task = get_object_or_404(Task, project=project, pk=task_id)
	return render(request, "projects/task_detail.html", {"project": project, "task": task})


def create_project(request):
	if request.method == "POST":
		form = ProjectCreationForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponse("Project creation successful.")
		else:
			return HttpResponse("The form is invalid.")
	else:
		form = ProjectCreationForm()
		return render(request, 'projects/create_project.html', {'form': form})


def create_task(request):
	if request.method == "POST":
		form = TaskCreationForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponse("Task creation successful.")
	else:
		form = TaskCreationForm()
		return render(request, 'projects/create_task.html', {'form': form})


def create_issue(request):
	if request.method == "POST":
		form = IssueCreationForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponse("Issue submitted successfully.")
		else:
			return render(request, "projects/invalid_form.html", {"form": form})
	else:
		form = IssueCreationForm()
		return render(request, 'projects/create_issue.html', {'form': form})


def issue_list(request):
	issues = Issue.objects.all()
	return render(request, 'projects/issue_list.html', {'issues': issues})


def issue_detail(request, issue_id):
	issue = get_object_or_404(Issue, pk=issue_id)
	return render(request, 'projects/issue_detail.html', {'issue': issue})

projects/templates/projects/base.html
{% load i18n static %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" dir="{{ LANGUAGE_BIDI|yesno:'rtl,ltr,auto' }}">
<head>
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "admin/css/base.css" %}{% endblock %}">
{% if not is_popup and is_nav_sidebar_enabled %}
  <link rel="stylesheet" type="text/css" href="{% static "admin/css/nav_sidebar.css" %}">
  <script src="{% static 'admin/js/nav_sidebar.js' %}" defer></script>
{% endif %}
{% block extrastyle %}{% endblock %}
{% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% static "admin/css/rtl.css" %}{% endblock %}">{% endif %}
{% block extrahead %}{% endblock %}
{% block responsive %}
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/responsive.css" %}">
    {% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% static "admin/css/responsive_rtl.css" %}">{% endif %}
{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE">{% endblock %}
</head>

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}"
  data-admin-utc-offset="{% now "Z" %}">

<!-- Container -->
<div id="container">

    {% if not is_popup %}
    <!-- Header -->
    {% block header %}
    <div id="header">
        <div id="branding">
        {% block branding %}{% endblock %}
        </div>
        {% block usertools %}
        {% if has_permission %}
        <div id="user-tools">
            {% block welcome-msg %}
                {% translate 'Welcome,' %}
                <strong>{% firstof user.get_short_name user.get_username %}</strong>.
            {% endblock %}
            {% block userlinks %}
                {% if site_url %}
                    <a href="{{ site_url }}">{% translate 'View site' %}</a> /
                {% endif %}
                {% if user.is_active and user.is_staff %}
                    {% url 'django-admindocs-docroot' as docsroot %}
                    {% if docsroot %}
                        <a href="{{ docsroot }}">{% translate 'Documentation' %}</a> /
                    {% endif %}
                {% endif %}
                {% if user.has_usable_password %}
                <a href="{% url 'admin:password_change' %}">{% translate 'Change password' %}</a> /
                {% endif %}
                <a href="{% url 'admin:logout' %}">{% translate 'Log out' %}</a>
            {% endblock %}
        </div>
        {% endif %}
        {% endblock %}
        {% block nav-global %}{% endblock %}
    </div>
    {% endblock %}
    <!-- END Header -->
    {% block breadcrumbs %}
    <div class="breadcrumbs">
    <a href="{% url 'admin:index' %}">{% translate 'Home' %}</a>
    {% if title %} &rsaquo; {{ title }}{% endif %}
    </div>
    {% endblock %}
    {% endif %}

    <div class="main" id="main">
      {% if not is_popup and is_nav_sidebar_enabled %}
        {% block nav-sidebar %}
          {% include "admin/nav_sidebar.html" %}
        {% endblock %}
      {% endif %}
      <div class="content">
        {% block messages %}
          {% if messages %}
            <ul class="messagelist">{% for message in messages %}
              <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
            {% endfor %}</ul>
          {% endif %}
        {% endblock messages %}
        <!-- Content -->
        <div id="content" class="{% block coltype %}colM{% endblock %}">
          {% block pretitle %}{% endblock %}
          {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
          {% block content_subtitle %}{% if subtitle %}<h2>{{ subtitle }}</h2>{% endif %}{% endblock %}
          {% block content %}
            {% block object-tools %}{% endblock %}
            {{ content }}
          {% endblock %}
          {% block sidebar %}{% endblock %}
          <br class="clear">
        </div>
        <!-- END Content -->
        {% block footer %}<div id="footer"></div>{% endblock %}
      </div>
    </div>
</div>
<!-- END Container -->
</body>
</html>

projects/templates/projects/create_issue.html
{% extends 'projects/base.html' %}

{% block title %}Create Issue{% endblock %}

{% block content %}
<form action="" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Submit">
</form>
{% endblock %}

projects/templates/projects/create_project.html
{% extends 'projects/base.html' %}

{% block title %}Create Project{% endblock %}

{% block content %}
<form action="" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Submit">
</form>
{% endblock %}

projects/templates/projects/create_task.html
{% extends 'projects/base.html' %}

{% block title %}Create Task{% endblock %}

{% block content %}
<form action="" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Submit">
</form>
{% endblock %}

projects/templates/projects/detail.html
{% extends 'projects/base.html' %}

{% block title %}Project Details{% endblock %}

{% block content %}
<div class="project-detail">
	<h1><strong>{{ project.title }}</strong> created by <strong>{{ project.company.name }}</strong></h1>
	<hr>
	<p><strong>Created on:</strong> <li>{{ project.created }}</li></p>
	<p><strong>Description:</strong> <li>{{ project.description }}</li></p>
	<p><strong>Budget:</strong> <li>${{ project.budget }}</li></p>
	<p><strong>Deadline:</strong> <li>{{ project.deadline }}</li></p>
	<p><strong>Employees:</strong></p>
	{% with project.user.all as users %}
	{% for user in users %}
		<p><strong>{{ user.first_name }} {{ user.last_name }}</strong></p>
	{% endfor %}
	{% endwith %}
</div>
<div class="task-list">
	<h1><strong>Tasks:</strong></h1>
	<button class="btn btn-primary"><a href="{% url 'projects:create_task' %}">Create New Task</a></button>
	{% for task in project.task_set.all %}
		<p><a href="{{ task.get_absolute_url }}">{{ task.title }}</a></p>
	{% empty %}
		<p>There are no tasks yet.</p>
	{% endfor %}
</div>
<div class="issues">
	<h1><strong>Issues:</strong></h1>
	<button class="btn btn-primary"><a href="{% url 'projects:create_issue' %}">Add Issue</a></button>
	{% for issue in project.issue_set.all %}
		<p>{{ issue.title }}</p>
	{% empty %}
		No issues at the moment.
	{% endfor %}
</div>
{% endblock %}

projects/templates/projects/invalid_form.html
{% extends 'projects/base.html' %}

{% block title %}Invalid Form{% endblock %}

{% block content %}
<form action="" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Submit">
</form>
{% endblock %}

projects/templates/projects/issue_detail.html
{% extends 'projects/base.html' %}
{% load static %}

{% block title %}{{ issue.title }}{% endblock %}

{% block content %}
<div class="issue">
	<h1><strong>{{ issue.title }}</strong></h1>
	{% if issue.image %}
		<p><img src="{% static 'issue.image.url' %}"></p>
	{% endif %}
	<p><strong>Description: </strong><li>{{ issue.description }}</li></p>
	<p><strong>Threat stage: </strong><li>{{ issue.get_threat_level_display }}</li></p>
	<p><strong>Deadline: </strong><li>{{ issue.deadline }}</li></p>
	{% for user in issue.submitted_by.all %}
		<p><strong>Submitted by: </strong><li>{{ user.username }}</li></p>
	{% endfor %}
</div>
{% endblock %}

projects/templates/projects/issue_list.html
{% extends 'projects/base.html' %}

{% block title %}Issues{% endblock %}

{% block content %}
<div class="issues">
	{% for issue in issues %}
		<p><strong>{{ issue.title }}</strong></p>
	{% empty %}
		No issues at the moment.
	{% endfor %}
</div>
{% endblock %}

projects/templates/projects/list.html
{% extends 'projects/base.html' %}

{% block title %}Projects{% endblock %}

{% block content %}
<div class="project-list">
	{% for project in projects %}
		<a href="{{ project.get_absolute_url }}"><h3>{{ project.title }}</h3></a>
	{% endfor %}
</div>
{% endblock %}

projects/templates/projects/task_detail.html
{% extends 'projects/base.html' %}

{% block title %}Task Detail{% endblock %}

{% block content %}
<div class="task-detail">
	<p>Title: {{ task.title }}</p>
	<p>Created on: <strong>{{ task.created }}</strong> Last updated: <strong>{{ task.updated }}</strong></p>
	<p>Description: {{ task.description }}</p>
</div>
<div class="issues">
	<h1><strong>Issues:</strong></h1>
	<button class="btn btn-primary"><a href="{% url 'projects:create_issue' %}">Add Issue</a></button>
	{% for issue in task.issue_set.all %}
		<p>{{ issue.title }}</p>
	{% empty %}
		No issues at the moment.
	{% endfor %}
</div>
{% endblock %}

projects/templates/projects/task_list.html
{% extends 'projects/base.html' %}

{% block title %}Tasks{% endblock %}

{% block content %}
<div class="task-list">
	{% for task in tasks %}
		<p><a href="{{ task.get_absolute_url }}">{{ task.title }}</a></p>
	{% empty %}
		There are no tasks yet.
	{% endfor %}
</div>
{% endblock %}